services:
  server:
    image: rival-music-server
    build: 
      context: ./server
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
      - /server/node_modules
      - /server/audio
  app:
    image: rival-music-client
    build: 
      context: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

